- hosts: web
  become: yes

  tasks:

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Copy App Files
      copy:
        src: ../app/
        dest: /home/ubuntu/myapp/
        mode: '0755'

    - name: Build Docker Image
      command: docker build -t my-flask-app /home/ubuntu/myapp

    - name: Run Docker Container
      docker_container:
        name: flask-container
        image: my-flask-app
        state: started
        recreate: yes
        restart_policy: always
        ports:
          - "5000:5000"
