name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Terraform Destroy (cleanup old infra)
        run: cd terraform && terraform destroy -auto-approve || true

      - name: Terraform Apply
        run: cd terraform && terraform apply -auto-approve

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.AWS_SSH_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Add EC2 to known hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 13.62.104.49 >> ~/.ssh/known_hosts

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible sshpass

      - name: Clean unused Docker data
        command: docker system prune -af

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory.ini ansible/install_docker.yml

      - name:  Puts Image on EC2 instance.
        run: scp -i key.pem -r . ubuntu@13.62.104.49:/home/ubuntu/myapp
        
      - name: Build Docker Image
        run: docker build -t my-flask-app ./app

      - name: Run Docker Container
        run: docker run -d -p 80:5000 my-flask-app
